const constants = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  FETCHING: 'FETCHING',
  ADD_ALERT: 'ADD_ALERT',
  CLEAR_ALERT: 'CLEAR_ALERT',
  CANCEL_FETCHING: 'CANCEL_FETCHING',
  ADD_USER_INFO: 'ADD_USER_INFO',
};

export default constants;